MFB:
  email: Anna.Han@cn.bosch.com
  name: Han Anna
MFC:
  email: Long.Cheng@cn.bosch.com
  name: Cheng Long
MFD:
  email: Juanhong.Chen@cn.bosch.com
  name: Chen Juanhong
MFE:
  email: ''
  name: Wu Jinhong
MFF:
  email: ''
  name: Guo Xin
MFG:
  email: jiajia.LIU@cn.bosch.com
  name: Liu Jiajia
MFH:
  email: Xuelai.JIN@cn.bosch.com
  name: Jin Xuelai
MFI:
  email: ''
  name: Zheng Crystal
MFJ:
  email: Shirley.LI@cn.bosch.com
  name: Li Shirley
MFK:
  email: Shengji.ZHANG@cn.bosch.com
  name: Zhang Shengji
MFL:
  email: Yachen.WANG2@cn.bosch.com
  name: Wang Yachen
MFM:
  email: Qi.WANG6@cn.bosch.com
  name: Wang Qi
MFN:
  email: ''
  name: Ma Qianmin
MFO:
  email: Bruce.WANG3@cn.bosch.com
  name: Wang Bruce
MFP:
  email: Jia.Shen@cn.bosch.com
  name: Shen Jia
MFQ:
  email: Aichen.XU@cn.bosch.com
  name: Xu Aichen
MFR:
  email: ''
  name: Zhuang Zhongkang
MFS:
  email: Shuangshuang.YAN@cn.bosch.com
  name: Yan Shuangshuang
MFT:
  email: Lewis.CHEN@cn.bosch.com
  name: Chen Lewis
MFW:
  email: Connor.TIAN@cn.bosch.com
  name: Tian Connor
MFX:
  email: Veronica.WU@cn.bosch.com
  name: Wu Veronica
MFY:
  email: Yu.WEI2@cn.bosch.com
  name: Wei Yu
MJA:
  email: Zhengwei.Zhang2@cn.bosch.com
  name: Zhang Zhengwei
MJB:
  email: Ruijun.Fu@cn.bosch.com
  name: Fu Ruijun
MJD:
  email: Li.YANG5@cn.bosch.com
  name: Yang Li
MJE:
  email: Wenming.YAN@cn.bosch.com
  name: Yan Wenming
MJF:
  email: Liang.HUANG6@cn.bosch.com
  name: Huang Liang
MJG:
  email: Meili.ZHENG@cn.bosch.com
  name: Zheng Meili
MJH:
  email: Jinping.YU@cn.bosch.com
  name: Yu Jinping
MJI:
  email: Li.YANG5@cn.bosch.com
  name: YANG Li
MJJ:
  email: Wenchao.Liu@cn.bosch.com
  name: Liu Wenchao
MJK:
  email: Xurong.JIANG@cn.bosch.com
  name: Jiang Xurong
MJL:
  email: Jingshan.ZHAO@cn.bosch.com
  name: Zhao Jingshan
MJM:
  email: Li.REN@cn.bosch.com
  name: Ren Li
MJT:
  email: ''
  name: Yu Hao
